[[Elfutils]]
arch = "aarch64"
git-tree-sha1 = "3d46bdbf281fbc6da469f2116fdfdf2ccba6433b"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "5896e1560435e8d44650c846a495cae13502555f333f04fef043effe4d0a3a16"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.196.0+0/Elfutils.v0.196.0.aarch64-linux-gnu.tar.gz"
[[Elfutils]]
arch = "aarch64"
git-tree-sha1 = "ad25c508de06f76eba9e8921615956eac4658c33"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "165bec4c0d218c240d0bd8397e313115593b6cea58f67f22b7633f1efee0bb25"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.196.0+0/Elfutils.v0.196.0.aarch64-linux-musl.tar.gz"
[[Elfutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "95506254f9b28ab144326991ce7fd22bf4ff1e04"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "0e2d4002a49a54406b91a2c4cd6353b057331251257445c386df4ae0f1c03342"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.196.0+0/Elfutils.v0.196.0.armv6l-linux-gnueabihf.tar.gz"
[[Elfutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e2b91bb0351bd6a484cae2b29603dc0708bfd721"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "9e3cb8844681f663311f1b6c1f9cc21e765e63de5b10e8f5e0a4008a22b70da9"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.196.0+0/Elfutils.v0.196.0.armv6l-linux-musleabihf.tar.gz"
[[Elfutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8468b1ccea0c5fdef1fde0af14304b0fb2d8e301"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "17dbe68f817419ab4b491d35cdca9acd5c2abb63e4aa2ad9e6d681f4b55860e2"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.196.0+0/Elfutils.v0.196.0.armv7l-linux-gnueabihf.tar.gz"
[[Elfutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "20d1e5df706c098b4f2db496877595bbfd3de993"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "dfc0090bba752951fa9f128e9a2001a565b3d12fb7b5b9de83677cf8f5fd207d"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.196.0+0/Elfutils.v0.196.0.armv7l-linux-musleabihf.tar.gz"
[[Elfutils]]
arch = "i686"
git-tree-sha1 = "c76914f790676dd327ce80489e1c56bd889fa485"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "14e06603929380b48e902fe133bd5e0eea3408fc01a2e2daef2b2b408c545655"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.196.0+0/Elfutils.v0.196.0.i686-linux-gnu.tar.gz"
[[Elfutils]]
arch = "i686"
git-tree-sha1 = "5471503f33f60f96ba4c5b3e9f9ac404840fc42c"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "0b5aff0953f1cdf018ae5e5944b6b6eed7d3a85fb25c3b79080cc35f2edf29cf"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.196.0+0/Elfutils.v0.196.0.i686-linux-musl.tar.gz"
[[Elfutils]]
arch = "powerpc64le"
git-tree-sha1 = "f3d148ac3d923bc10b9a05e35442c3675c9b2a34"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "f3f37828519e53c5490bfd6bbe101b5b43bb1ffd79785deb57da2b0dd1d04c41"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.196.0+0/Elfutils.v0.196.0.powerpc64le-linux-gnu.tar.gz"
[[Elfutils]]
arch = "riscv64"
git-tree-sha1 = "3a661ef76650ddd9dec10c94a4ba466e515fef03"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "e83540a959de340dab6f47d57b4af20605e58a833d0bd28edeb35684fd3c3d85"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.196.0+0/Elfutils.v0.196.0.riscv64-linux-gnu.tar.gz"
[[Elfutils]]
arch = "x86_64"
git-tree-sha1 = "6862ecfbc5de0ab38e14abedc8c0abf6b60a65ad"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "988707fedff8643e0781d1775684f50490f0f792df51bbdb076cd9af1c480518"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.196.0+0/Elfutils.v0.196.0.x86_64-linux-gnu.tar.gz"
[[Elfutils]]
arch = "x86_64"
git-tree-sha1 = "8e7ef036d50d41211ec24dcb79ffc9e645405bb0"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "ad2240e333c0679542bfa2578f7b4d1e3ab7d46f6f7c2904cbd1853608be5646"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.196.0+0/Elfutils.v0.196.0.x86_64-linux-musl.tar.gz"
