[[Elfutils]]
arch = "aarch64"
git-tree-sha1 = "46f9e58f6b8e47c738cf9e1211338a001e3b3e75"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "6749e711847afd98a8d45f21cdca5af76e54018fbd94fa947575e437067d9b58"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+1/Elfutils.v0.182.0.aarch64-linux-gnu.tar.gz"
[[Elfutils]]
arch = "aarch64"
git-tree-sha1 = "5db8bdde6d3caf1f0ce69d99b6ce65ab9d05e6ef"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "69df47841d93c8576473597bd0b421f241f5e0a69ad1c62e87288d2138f5afa5"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+1/Elfutils.v0.182.0.aarch64-linux-musl.tar.gz"
[[Elfutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2cbad07ffa1b8dcf150f3adbf822bccf2b52e80b"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "445ef03ee52a37239c3ac0379cf1d54f32c685575c348117a5b06b7e11a0fd56"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+1/Elfutils.v0.182.0.armv7l-linux-gnueabihf.tar.gz"
[[Elfutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cdb2d2a06ec2b2b96fc78ecd0c3f2e497fe7fda0"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "11e817511c0df9d5485bc0dc287be1ef35dc0a74770156fcf525e490b70899cb"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+1/Elfutils.v0.182.0.armv7l-linux-musleabihf.tar.gz"
[[Elfutils]]
arch = "i686"
git-tree-sha1 = "d9dcd522b90740e069d6e15dc19de974ae0127da"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "6646b017ccc026a6672798c56a052dec9df5cdaddb8906eaecb5c603ec45c5a0"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+1/Elfutils.v0.182.0.i686-linux-gnu.tar.gz"
[[Elfutils]]
arch = "i686"
git-tree-sha1 = "dafcbb31fffa017f8e27b5b2db1a399cbe3b3942"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "e6aaa6d9b245c48e360d078dd17444c91fbd5d16995b1053d754a7a1a538d5bc"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+1/Elfutils.v0.182.0.i686-linux-musl.tar.gz"
[[Elfutils]]
arch = "powerpc64le"
git-tree-sha1 = "283c1d2c2edeaa09f7518bc357fa757c2736f77e"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "61bc32a03121e0906e3592177fa5a758c310685f77e1f82dfc02ebaa848e1c1d"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+1/Elfutils.v0.182.0.powerpc64le-linux-gnu.tar.gz"
[[Elfutils]]
arch = "x86_64"
git-tree-sha1 = "89d0da1143726d842c3d358bd51fe11bfb29a054"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "122e6d7cee6aca813d1db50890fa57d81a9a00e5deec52a16ea4102406458ee5"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+1/Elfutils.v0.182.0.x86_64-linux-gnu.tar.gz"
[[Elfutils]]
arch = "x86_64"
git-tree-sha1 = "de82dd6781d06d4eceafbffa58b7633aa512628b"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "2fe9e444c561a4f51f6da71af6aa095df10b7324c6134ed06d7c0a223b40d3bc"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+1/Elfutils.v0.182.0.x86_64-linux-musl.tar.gz"
