[[Elfutils]]
arch = "armv7l"
git-tree-sha1 = "a0d22d519bd943be7313530092f1e60ba21d7d31"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "c5788cc6b353e059ac4a9b8830078f7de465d0607b7372dbe627360342f82bda"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.177.0+1/Elfutils.v0.177.0.armv7l-linux-gnueabihf.tar.gz"
[[Elfutils]]
arch = "aarch64"
git-tree-sha1 = "30c3ccc44de78073ec82312464b7e0e67c053670"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "82469057bbbfe9078c74ed17f4979877f648785b0fe35f8968396dfdbe49fdd5"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.177.0+1/Elfutils.v0.177.0.aarch64-linux-gnu.tar.gz"
[[Elfutils]]
arch = "i686"
git-tree-sha1 = "37db11d8a1b309283c1de855b67e8904478e8042"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "a2c2d1c49453777d2f107d5843e513dd88bff92f1fa550dc2ca837a3f59617d3"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.177.0+1/Elfutils.v0.177.0.i686-linux-gnu.tar.gz"
[[Elfutils]]
arch = "x86_64"
git-tree-sha1 = "784c7994b28ae60422588d53d971ca3f0e9b7efa"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "fa27daa70b75634c62566e605f345f158cbd55fd0f4139153267716ee45d933f"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.177.0+1/Elfutils.v0.177.0.x86_64-linux-gnu.tar.gz"
[[Elfutils]]
arch = "powerpc64le"
git-tree-sha1 = "b063ceb838f6346258007542717ad33736641c64"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "843acd8354da08b668906143a9dea2227891d5f4920ffad068681c283576ad93"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.177.0+1/Elfutils.v0.177.0.powerpc64le-linux-gnu.tar.gz"
