[[Elfutils]]
arch = "aarch64"
git-tree-sha1 = "d86fb6196e8dc533ae3e8e9aad058d2d2ceb6c93"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "8c94e8a13dd9351c50de04d42cee1a4311a6b7dc0cd409f4e09ff5ddc5f6c8a4"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+0/Elfutils.v0.182.0.aarch64-linux-gnu.tar.gz"
[[Elfutils]]
arch = "aarch64"
git-tree-sha1 = "aed58ccd826a1d6abfd05c5145c58be72a4a5eb0"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "c7de0ce8f3018c6cb28647041b7e7516e67d2887078b69f6e0b5b45d13c3017f"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+0/Elfutils.v0.182.0.aarch64-linux-musl.tar.gz"
[[Elfutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7ee7c8b4b73dfc66e8f5132fbf3af4b60ea07ab7"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "0082a332b56d6b7c5bbbb6375c202971f486d4c465b0f8e859300ae007819e67"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+0/Elfutils.v0.182.0.armv7l-linux-gnueabihf.tar.gz"
[[Elfutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1f68806002b98aa5a6629ac27b9f351ab47c2c4f"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "a0ae203b32938c3f2c57e2649b8988692efc56ab3d957d92cb7e9f0224a705d7"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+0/Elfutils.v0.182.0.armv7l-linux-musleabihf.tar.gz"
[[Elfutils]]
arch = "i686"
git-tree-sha1 = "6d15bc2e0a92c0877a18d4216f14d8bb71afd18b"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "ec6a75869ac8f1ac4c3498e08624899c34b4cee7e72d0c18f0d8eda4b6bfd72d"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+0/Elfutils.v0.182.0.i686-linux-gnu.tar.gz"
[[Elfutils]]
arch = "i686"
git-tree-sha1 = "53f12ca269944f2f6e171e56652fbb0975f0ea26"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "92348b15d228e504ee38521f1662f0d018ec5474a06fa462cf7de0f5660b613f"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+0/Elfutils.v0.182.0.i686-linux-musl.tar.gz"
[[Elfutils]]
arch = "powerpc64le"
git-tree-sha1 = "0b8ba7bf73245f88f7642507bd80429734139c6b"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "28725f075b6649c36a275428d5bb756ac27cff1ab66add6fc4ec893a1a224575"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+0/Elfutils.v0.182.0.powerpc64le-linux-gnu.tar.gz"
[[Elfutils]]
arch = "x86_64"
git-tree-sha1 = "509fb32a30e2400f753b0ed99f23e886fd7065d8"
libc = "glibc"
os = "linux"

    [[Elfutils.download]]
    sha256 = "b78b560aa61c02db178e3aaef51da6166bfa4df95b210a84285dec6e537d538e"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+0/Elfutils.v0.182.0.x86_64-linux-gnu.tar.gz"
[[Elfutils]]
arch = "x86_64"
git-tree-sha1 = "32a6cb85ec96a042abebba2b69c1b5f364fce3e9"
libc = "musl"
os = "linux"

    [[Elfutils.download]]
    sha256 = "5ff25cc38f77fa4de67f45a3972923cac983d8288a0600c8f832af1caf2d92f0"
    url = "https://github.com/JuliaBinaryWrappers/Elfutils_jll.jl/releases/download/Elfutils-v0.182.0+0/Elfutils.v0.182.0.x86_64-linux-musl.tar.gz"
